after_success:
- coveralls
before_install:
- sudo apt-get update
- pip install -r requirements_dev.txt
- python setup.py install
deploy:
  provider: pypi
  user: arkottke
  password:
    secure: kTrTiuxg73oGngQjCXhKsif6Jsd271uTEzAMQLaf9xYUMyS0AtG1qsNxqBWBvXHkuc+pcUh0roydK7ytoYRtrtyNDgcTz6h38FvWnkn2qq/wwyBYhLfWGpjo0v26qPA4w1XyQKnm8TQNQXZ0sG0UHy3sBDLp5RoaF9Kr8TtO7bM=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: arkottke/pyrotd
language: python
python:
- '3.6'
script:
- pytest -v
